# Generated by Django 2.0.3 on 2018-06-14 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('close_date', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('SAUDE', 'Saude'), ('EDUCACIONAL', 'Educacional'), ('CORTE DE CABELO', 'Corte de cabelo'), ('OUTRA CATEGORIA', 'Outra Categoria')], default='SAUDE', max_length=40)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('openHour', models.TimeField()),
                ('closeHour', models.TimeField()),
                ('telefone', models.CharField(max_length=15)),
                ('cidade', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=140)),
                ('cep', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('communityaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='divulga.CommunityAction')),
                ('item_name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('email', models.CharField(max_length=140)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('divulga.communityaction',),
        ),
        migrations.CreateModel(
            name='HealthService',
            fields=[
                ('communityaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='divulga.CommunityAction')),
                ('start_hour', models.TimeField()),
                ('close_hour', models.TimeField()),
                ('email', models.CharField(max_length=140)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('divulga.communityaction',),
        ),
        migrations.AddField(
            model_name='communityaction',
            name='establishment',
            field=models.ManyToManyField(to='divulga.Establishment'),
        ),
        migrations.AddField(
            model_name='communityaction',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_divulga.communityaction_set+', to='contenttypes.ContentType'),
        ),
    ]
