# Generated by Django 2.0.4 on 2018-05-28 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Divulgacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEvento', models.CharField(max_length=140)),
                ('telefone', models.CharField(max_length=140)),
                ('cidade', models.CharField(max_length=140)),
                ('endereco', models.CharField(max_length=140)),
                ('horarioInicio', models.CharField(max_length=20)),
                ('horarioFim', models.CharField(max_length=20)),
                ('data', models.CharField(max_length=20)),
                ('categoria', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('openHour', models.TimeField()),
                ('closeHour', models.TimeField()),
                ('telefone', models.CharField(max_length=15)),
                ('cidade', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=140)),
                ('cep', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('communityaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='divulga.CommunityAction')),
                ('item_name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('divulga.communityaction',),
        ),
        migrations.CreateModel(
            name='HealthService',
            fields=[
                ('communityaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='divulga.CommunityAction')),
                ('start_hour', models.TimeField()),
                ('close_hour', models.TimeField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('divulga.communityaction',),
        ),
        migrations.AddField(
            model_name='establishment',
            name='community_action',
            field=models.ManyToManyField(blank=True, null=True, to='divulga.CommunityAction'),
        ),
        migrations.AddField(
            model_name='communityaction',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_divulga.communityaction_set+', to='contenttypes.ContentType'),
        ),
    ]
