# Generated by Django 2.0.4 on 2018-05-24 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Divulgacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeEvento', models.CharField(max_length=140)),
                ('telefone', models.CharField(max_length=140)),
                ('cidade', models.CharField(max_length=140)),
                ('bairro', models.CharField(max_length=140)),
                ('endereco', models.CharField(max_length=140)),
                ('cep', models.CharField(max_length=140)),
                ('horarioInicio', models.CharField(max_length=20)),
                ('horarioFim', models.CharField(max_length=20)),
                ('data', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
