# Generated by Django 2.0.4 on 2018-06-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoluntaryService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('cidade', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=140)),
                ('description', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=140)),
                ('openHour', models.TimeField()),
                ('closeHour', models.TimeField()),
            ],
        ),
    ]
