# Generated by Django 2.0.4 on 2018-05-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulga', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='divulgacoes',
            name='user',
        ),
        migrations.DeleteModel(
            name='Divulgacoes',
        ),
    ]
