# Generated by Django 2.0.4 on 2018-06-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulga', '0003_auto_20180605_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='categoria',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
