# Generated by Django 2.0.4 on 2018-06-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulga', '0005_auto_20180606_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='establishment',
            name='category',
        ),
        migrations.AddField(
            model_name='communityaction',
            name='category',
            field=models.CharField(choices=[('SA', 'Saude'), ('ED', 'Educacional'), ('C2', 'Categoria2')], default='SA', max_length=2),
        ),
    ]
