# Generated by Django 2.0.4 on 2018-06-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulga', '0007_auto_20180607_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityaction',
            name='category',
            field=models.CharField(choices=[('SAUDE', 'Saude'), ('EDUCACIONAL', 'Educacional'), ('C2', 'Categoria2')], default='SAUDE', max_length=40),
        ),
    ]
