# Generated by Django 2.0.4 on 2018-06-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulga', '0008_auto_20180607_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityaction',
            name='category',
            field=models.CharField(choices=[('SAUDE', 'Saude'), ('EDUCACIONAL', 'Educacional'), ('CORTE DE CABELO', 'Corte de cabelo'), ('OUTRA CATEGORIA', 'Outra Categoria')], default='SAUDE', max_length=40),
        ),
    ]
